# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: vanillin
# description will be included in the image's metadata
description: Custom image based on VanillaOS testing.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/vanilla-os/desktop
base-image-type: vanilla
image-version: main # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - io.github.flattool.Warehouse

  - type: script
    scripts:
      - abroot.sh

  # - type: signing # this sets up the proper policy & signing files for signed images to work fully

